# Site settings
title:       tajquangkhanhs's blog
email:       quangkhanh007@gmail.com
author:      taj quangkhanhs
description: "Learning for your brain LoL xD"
baseurl:     ""
url:         "http://tqk.pw"
date_format: "%b %-d, %Y"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  false
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: bytekve
bitbucket_username:
stackoverflow_id:
twitter_username: vlpm4st3r
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: false

# Build settings
highlighter: pygments
markdown:     kramdown
permalink:    pretty
paginate:     4
sass:
  compressed: true
